<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1.2 (Python 3.9.0 on win32)" generated="20211029 17:27:19.383" rpa="false" schemaversion="2">
<suite id="s1" name="Variaveis" source="C:\Projetos\Curso Prime 25-10-21\prime_experts_turma_4\variaveis">
<suite id="s1-s1" name="Test Variavel" source="C:\Projetos\Curso Prime 25-10-21\prime_experts_turma_4\variaveis\test_variavel.robot">
<test id="s1-s1-t1" name="cenario: imprimindo minha Lista de frutas">
<kw name="imprimir Lista de Lista de frutas" library="resource">
<msg timestamp="20211029 17:27:19.418" level="TRACE">Arguments: [  ]</msg>
<kw name="Log To Console" library="BuiltIn">
<arg>\n\nimprimindo nossa lista de frutas: \n${Lista_frutas}\n</arg>
<doc>Logs the given message to the console.</doc>
<msg timestamp="20211029 17:27:19.419" level="TRACE">Arguments: [ "\n\nimprimindo nossa lista de frutas: \n['morango', 'ma√ßa', 'pera', 'kiwi', 'acerola']\n" ]</msg>
<msg timestamp="20211029 17:27:19.419" level="TRACE">Return: None</msg>
<status status="PASS" starttime="20211029 17:27:19.418" endtime="20211029 17:27:19.419"/>
</kw>
<msg timestamp="20211029 17:27:19.420" level="TRACE">Return: None</msg>
<status status="PASS" starttime="20211029 17:27:19.418" endtime="20211029 17:27:19.420"/>
</kw>
<tag>frutas</tag>
<status status="PASS" starttime="20211029 17:27:19.417" endtime="20211029 17:27:19.420"/>
</test>
<status status="PASS" starttime="20211029 17:27:19.404" endtime="20211029 17:27:19.421"/>
</suite>
<status status="PASS" starttime="20211029 17:27:19.384" endtime="20211029 17:27:19.423"/>
</suite>
<statistics>
<total>
<stat pass="1" fail="0" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="1" fail="0" skip="0">frutas</stat>
</tag>
<suite>
<stat pass="1" fail="0" skip="0" id="s1" name="Variaveis">Variaveis</stat>
<stat pass="1" fail="0" skip="0" id="s1-s1" name="Test Variavel">Variaveis.Test Variavel</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20211029 17:27:19.409" level="ERROR">Error in file 'C:\Projetos\Curso Prime 25-10-21\prime_experts_turma_4\variaveis\resource.robot' on line 5: Setting variable '&amp;{pessoa}' failed: Multiple errors:
- Invalid dictionary variable item 'sexo:F'. Items must use 'name=value' syntax or be dictionary variables themselves.
- Invalid dictionary variable item 'cel:988944344'. Items must use 'name=value' syntax or be dictionary variables themselves.</msg>
</errors>
</robot>
